//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVA_backend.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Rating = new HashSet<Rating>();
        }
    
        public int Id { get; set; }
        public int NmbrOfChildren { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public bool IsStudent { get; set; }
        public string Language { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public int Difficulty { get; set; }
        public bool SendNewsletter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Rating { get; set; }
    }
}
